name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/iconly-light-arrow-left.png
    - assets/page-1/images/iconly-light-arrow-left-NYi.png
    - assets/page-1/images/iconly-light-location.png
    - assets/page-1/images/mask-group.png
    - assets/page-1/images/asset-1-8-5.png
    - assets/page-1/images/mask-group-Vzi.png
    - assets/page-1/images/bi-credit-card-2-front-fill.png
    - assets/page-1/images/iconly-light-profile.png
    - assets/page-1/images/iconly-light-setting.png
    - assets/page-1/images/iconly-light-profile-Vy4.png
    - assets/page-1/images/screen-shot-2021-01-19-at-1007-1.png
    - assets/page-1/images/iconly-light-bag.png
    - assets/page-1/images/mask-group-98N.png
    - assets/page-1/images/saly-17.png
    - assets/page-1/images/asset-1-8-5-E6N.png
    - assets/page-1/images/iconly-light-arrow-left-wN2.png
    - assets/page-1/images/iconly-light-message.png
    - assets/page-1/images/screen-shot-2021-01-19-at-1002-1.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/iconly-light-delete.png
    - assets/page-1/images/mask-group-uyk.png
    - assets/page-1/images/auto-group-ewtz.png
    - assets/page-1/images/mask-group-nXk.png
    - assets/page-1/images/group-6.png
    - assets/page-1/images/chevron-left.png
    - assets/page-1/images/iconly-light-search.png
    - assets/page-1/images/asset-2-8-2.png
    - assets/page-1/images/mask-group-qiz.png
    - assets/page-1/images/vector-jZU.png
    - assets/page-1/images/auto-group-qvcn.png
    - assets/page-1/images/rectangle-4.png
    - assets/page-1/images/iconly-light-logout.png
    - assets/page-1/images/iconly-light-arrow-left-TmL.png
    - assets/page-1/images/auto-group-6yxs.png
    - assets/page-1/images/iconly-light-message-9Xg.png
    - assets/page-1/images/iconly-light-buy.png
    - assets/page-1/images/mask-group-D1k.png
    - assets/page-1/images/mask-group-LcA.png
    - assets/page-1/images/mask-group-fuL.png
    - assets/page-1/images/menu.png
    - assets/page-1/images/iconly-light-location-zHQ.png
    - assets/page-1/images/iconly-light-arrow-left-bvi.png
    - assets/page-1/images/menu-K62.png
    - assets/page-1/images/iconly-light-heart.png
    - assets/page-1/images/iconly-light-profile-qBp.png
    - assets/page-1/images/iconly-light-arrow-left-vDG.png
    - assets/page-1/images/iconly-light-lock.png
    - assets/page-1/images/chevron-left-PsY.png
    - assets/page-1/images/iconly-light-arrow-left-iev.png
    - assets/page-1/images/iconly-light-lock-3hC.png
    - assets/page-1/images/vector-fmc.png
    - assets/page-1/images/auto-group-4bge.png
    - assets/page-1/images/auto-group-j18n.png
    - assets/page-1/images/sally-4.png
    - assets/page-1/images/iconly-light-arrow-left-eBL.png
    - assets/page-1/images/bi-credit-card-2-front-fill-WzE.png
    - assets/page-1/images/saly-17-NS6.png
    - assets/page-1/images/iconly-light-lock-wrS.png
    - assets/page-1/images/home-2.png
    - assets/page-1/images/iconly-light-arrow-left-M9U.png
    - assets/page-1/images/iconly-light-call.png
    - assets/page-1/images/.png
    - assets/page-1/images/rectangle-6.png
    - assets/page-1/images/mask-group-Kfp.png
    - assets/page-1/images/rectangle-6-vzW.png
    - assets/page-1/images/saly-10.png
    - assets/page-1/images/saly-11.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
